from fastapi import APIRouter,Depends,HTTPException,Query,Response
from core.exceptions import NotFoundError,ConflictError,ValidationError
from operator_auth.context import OperatorContext
from operator_auth.dependencies import legacy_basic_agency_context
from operator_auth.exceptions import PlatformAdminAgencyRequired
from . import service
from .schemas import *
router=APIRouter(prefix='/api/buy',tags=['buy'])
def tr(fn,*a,**k):
    try:return fn(*a,**k)
    except NotFoundError as e:raise HTTPException(404,str(e))
    except ConflictError as e:raise HTTPException(409,str(e))
    except ValidationError as e:raise HTTPException(400,str(e))
    except PlatformAdminAgencyRequired as e:raise HTTPException(403,str(e))
    except ValueError as e:raise HTTPException(422,str(e))
@router.get('/dashboard')
def dashboard(ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.dashboard_scoped,ctx)
@router.post('/requests',status_code=201)
def create_request(p:BuyRequestCreate,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.create_request_scoped,ctx,p)
@router.get('/requests')
def list_requests(limit:int=Query(50,ge=1,le=200),offset:int=Query(0,ge=0),search:str|None=None,status:str|None=None,priority:str|None=None,urgency:str|None=None,contact_id:int|None=None,lead_id:int|None=None,assigned_to:str|None=None,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return {'items':tr(service.list_requests_scoped,ctx,limit,offset,search,status,priority,urgency,contact_id,lead_id,assigned_to)}
@router.get('/requests/{request_id}')
def get_request(request_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.get_request_scoped,ctx,request_id)
@router.patch('/requests/{request_id}')
def update_request(request_id:int,p:BuyRequestUpdate,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.update_request_scoped,ctx,request_id,p)
@router.delete('/requests/{request_id}')
def archive_request(request_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.archive_request_scoped,ctx,request_id)
@router.get('/requests/{request_id}/normalized')
def normalized(request_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.normalized_scoped,ctx,request_id)
@router.get('/requests/{request_id}/workflow')
def workflow(request_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.workflow_scoped,ctx,request_id)
@router.get('/requests/{request_id}/matches')
def matches(request_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return {'items':tr(service.list_matches_scoped,ctx,request_id)}
@router.post('/requests/{request_id}/matches/{match_id}/decision',status_code=201)
def match_decision(request_id:int,match_id:int,p:MatchDecision,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.match_decision_scoped,ctx,request_id,match_id,p)
@router.post('/requests/{request_id}/interactions',status_code=201)
def add_interaction(request_id:int,p:InteractionCreate,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.add_interaction_scoped,ctx,request_id,p)
@router.patch('/interactions/{interaction_id}')
def update_interaction(interaction_id:int,p:InteractionUpdate,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.update_interaction_scoped,ctx,interaction_id,p)
@router.delete('/interactions/{interaction_id}',status_code=204)
def delete_interaction(interaction_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):tr(service.delete_interaction_scoped,ctx,interaction_id);return Response(status_code=204)
@router.post('/requests/{request_id}/tasks',status_code=201)
def create_task(request_id:int,p:BuyTaskCreate,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.create_task_scoped,ctx,request_id,p)
@router.get('/requests/{request_id}/tasks')
def tasks(request_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return {'items':tr(service.list_tasks_scoped,ctx,request_id)}
@router.delete('/task-links/{link_id}',status_code=204)
def unlink_task(link_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):tr(service.unlink_task_scoped,ctx,link_id);return Response(status_code=204)
@router.post('/requests/{request_id}/history/notes',status_code=201)
def add_note(request_id:int,p:HistoryNoteCreate,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.add_note_scoped,ctx,request_id,p)
@router.post('/requests/{request_id}/locations',status_code=201)
def add_location(request_id:int,p:LocationCreate,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.add_location_scoped,ctx,request_id,p)
@router.delete('/locations/{location_id}',status_code=204)
def delete_location(location_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):tr(service.delete_location_scoped,ctx,location_id);return Response(status_code=204)
@router.post('/requests/{request_id}/typologies',status_code=201)
def add_typology(request_id:int,p:TypologyCreate,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.add_typology_scoped,ctx,request_id,p)
@router.delete('/typologies/{typology_id}',status_code=204)
def delete_typology(typology_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):tr(service.delete_typology_scoped,ctx,typology_id);return Response(status_code=204)
@router.post('/requests/{request_id}/features',status_code=201)
def add_feature(request_id:int,p:FeatureCreate,ctx:OperatorContext=Depends(legacy_basic_agency_context)):return tr(service.add_feature_scoped,ctx,request_id,p)
@router.delete('/features/{feature_id}',status_code=204)
def delete_feature(feature_id:int,ctx:OperatorContext=Depends(legacy_basic_agency_context)):tr(service.delete_feature_scoped,ctx,feature_id);return Response(status_code=204)
