from fastapi import APIRouter,HTTPException,Query,Response
from core.exceptions import NotFoundError,ConflictError,ValidationError
from . import service
from .schemas import *
router=APIRouter(prefix='/api/property',tags=['property'])
def tr(fn,*a,**k):
    try:return fn(*a,**k)
    except NotFoundError as e:raise HTTPException(404,str(e))
    except ConflictError as e:raise HTTPException(409,str(e))
    except ValidationError as e:raise HTTPException(400,str(e))
@router.get('/dashboard')
def get_dashboard():return tr(service.dashboard)
@router.get('/alerts')
def get_alerts():return tr(service.alerts)
@router.post('/properties',status_code=201)
def create_property(p:PropertyCreate):return tr(service.create_property,p)
@router.get('/properties')
def list_properties(limit:int=Query(50,ge=1,le=200),offset:int=Query(0,ge=0),search:str|None=None,status:str|None=None,classification:str|None=None,city:str|None=None,contact_id:int|None=None,lead_id:int|None=None,assigned_to:str|None=None,mandate_expiring:bool=False,missing_documents:bool=False):return {'items':tr(service.list_properties,limit,offset,search,status,classification,city,contact_id,lead_id,assigned_to,mandate_expiring,missing_documents)}
@router.get('/properties/{property_id}')
def get_property(property_id:int):return tr(service.get_property,property_id)
@router.patch('/properties/{property_id}')
def update_property(property_id:int,p:PropertyUpdate):return tr(service.update_property,property_id,p)
@router.delete('/properties/{property_id}')
def archive_property(property_id:int):return tr(service.archive_property,property_id)
@router.post('/properties/{property_id}/contacts',status_code=201)
def add_contact(property_id:int,p:PropertyContactCreate):return tr(service.add_contact,property_id,p)
@router.delete('/properties/{property_id}/contacts/{contact_id}/{role}',status_code=204)
def delete_contact(property_id:int,contact_id:int,role:str):tr(service.delete_contact,property_id,contact_id,role);return Response(status_code=204)
@router.post('/properties/{property_id}/leads',status_code=201)
def add_lead(property_id:int,p:PropertyLeadCreate):return tr(service.add_lead,property_id,p)
@router.delete('/properties/{property_id}/leads/{lead_id}',status_code=204)
def delete_lead(property_id:int,lead_id:int):tr(service.delete_lead,property_id,lead_id);return Response(status_code=204)
@router.post('/properties/{property_id}/documents',status_code=201)
def add_document(property_id:int,p:DocumentCreate):return tr(service.add_document,property_id,p)
@router.patch('/documents/{document_id}')
def update_document(document_id:int,p:DocumentUpdate):return tr(service.update_document,document_id,p)
@router.delete('/documents/{document_id}',status_code=204)
def delete_document(document_id:int):tr(service.delete_document,document_id);return Response(status_code=204)
@router.post('/properties/{property_id}/photos',status_code=201)
def add_photo(property_id:int,p:PhotoCreate):return tr(service.add_photo,property_id,p)
@router.patch('/photos/{photo_id}')
def update_photo(photo_id:int,p:PhotoUpdate):return tr(service.update_photo,photo_id,p)
@router.delete('/photos/{photo_id}',status_code=204)
def delete_photo(photo_id:int):tr(service.delete_photo,photo_id);return Response(status_code=204)
@router.get('/visits')
def list_visits(limit:int=Query(100,ge=1,le=500),offset:int=Query(0,ge=0),status:str|None=None,from_date:str|None=None,to_date:str|None=None):return {'items':tr(service.list_visits,limit,offset,status,from_date,to_date)}
@router.post('/properties/{property_id}/visits',status_code=201)
def add_visit(property_id:int,p:VisitCreate):return tr(service.add_visit,property_id,p)
@router.patch('/visits/{visit_id}')
def update_visit(visit_id:int,p:VisitUpdate):return tr(service.update_visit,visit_id,p)
@router.delete('/visits/{visit_id}',status_code=204)
def delete_visit(visit_id:int):tr(service.delete_visit,visit_id);return Response(status_code=204)
